"""v5_initial_schema

Revision ID: 578d92de7851
Revises: 
Create Date: 2026-05-02 19:53:20.066200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '578d92de7851'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('plan', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("plan IN ('free', 'pro', 'enterprise')", name='ck_users_plan'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('workspaces',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workspaces_owner_user_id'), ['owner_user_id'], unique=False)

    op.create_table('stores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('primary_url', sa.String(length=2000), nullable=True),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("platform IN ('google', 'youtube')", name='ck_stores_platform'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stores_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('analysis_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.BigInteger(), nullable=False),
    sa.Column('ai_function', sa.String(length=64), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('model_id', sa.String(length=128), nullable=False),
    sa.Column('input_review_ids', sa.JSON(), nullable=True),
    sa.Column('output_json', sa.JSON(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('cost_cents', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_class', sa.String(length=128), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("ai_function IN ('analyze', 'swot', 'reply', 'analyze_issue', 'marketing', 'weekly_plan', 'training_script', 'internal_email', 'chat')", name='ck_analysis_runs_function'),
    sa.CheckConstraint("status IN ('queued', 'running', 'succeeded', 'failed', 'cancelled')", name='ck_analysis_runs_status'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_runs', schema=None) as batch_op:
        batch_op.create_index('ix_analysis_runs_store_created', ['store_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_runs_store_id'), ['store_id'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.BigInteger(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('format', sa.String(length=16), nullable=False),
    sa.Column('file_path', sa.String(length=2000), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("format IN ('pdf', 'docx')", name='ck_reports_format'),
    sa.CheckConstraint("status IN ('queued', 'running', 'succeeded', 'failed')", name='ck_reports_status'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_store_id'), ['store_id'], unique=False)

    op.create_table('review_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.BigInteger(), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('external_url', sa.String(length=2000), nullable=False),
    sa.Column('last_scraped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_reviews_estimated', sa.Integer(), nullable=True),
    sa.CheckConstraint("source_type IN ('google_maps', 'youtube')", name='ck_review_sources_type'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_sources_store_id'), ['store_id'], unique=False)

    op.create_table('generated_assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_run_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('content_md', sa.Text(), nullable=True),
    sa.Column('content_html', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('generated_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_generated_assets_analysis_run_id'), ['analysis_run_id'], unique=False)

    op.create_table('scrape_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_class', sa.String(length=128), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('reviews_fetched_count', sa.Integer(), nullable=False),
    sa.Column('pagination_truncated', sa.Boolean(), nullable=False),
    sa.CheckConstraint("status IN ('queued', 'running', 'succeeded', 'failed', 'cancelled')", name='ck_scrape_jobs_status'),
    sa.ForeignKeyConstraint(['source_id'], ['review_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scrape_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scrape_jobs_source_id'), ['source_id'], unique=False)
        batch_op.create_index('ix_scrape_jobs_source_status', ['source_id', 'status'], unique=False)

    op.create_table('reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=False),
    sa.Column('scrape_job_id', sa.BigInteger(), nullable=True),
    sa.Column('external_id', sa.String(length=256), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['scrape_job_id'], ['scrape_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['review_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'external_id', name='uq_reviews_source_external')
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviews_scrape_job_id'), ['scrape_job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_source_id'), ['source_id'], unique=False)
        batch_op.create_index('ix_reviews_source_published', ['source_id', 'published_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index('ix_reviews_source_published')
        batch_op.drop_index(batch_op.f('ix_reviews_source_id'))
        batch_op.drop_index(batch_op.f('ix_reviews_scrape_job_id'))

    op.drop_table('reviews')
    with op.batch_alter_table('scrape_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_scrape_jobs_source_status')
        batch_op.drop_index(batch_op.f('ix_scrape_jobs_source_id'))

    op.drop_table('scrape_jobs')
    with op.batch_alter_table('generated_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generated_assets_analysis_run_id'))

    op.drop_table('generated_assets')
    with op.batch_alter_table('review_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_sources_store_id'))

    op.drop_table('review_sources')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_store_id'))

    op.drop_table('reports')
    with op.batch_alter_table('analysis_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_runs_store_id'))
        batch_op.drop_index('ix_analysis_runs_store_created')

    op.drop_table('analysis_runs')
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stores_workspace_id'))

    op.drop_table('stores')
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspaces_owner_user_id'))

    op.drop_table('workspaces')
    op.drop_table('users')
    # ### end Alembic commands ###
